# Teleop configuration for PS4 Navigation joystick.
teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.2
  scale_linear_turbo: 1.0
  axis_angular: 0
  scale_angular: 1.0
  enable_button: 4
  enable_turbo_button: 5
joy_node:
  deadzone: 0.02
  autorepeat_rate: 20
  dev: /dev/input/ps4
